# Continuous Integration with https://travis-ci.org/
language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode12
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - libwxgtk3.0-dev
            - libxml2-dev
            - libuchardet-dev 
            - libssh-dev
            - libsmbclient-dev
            - libnfs-dev
            - libneon27-dev
            - libarchive-dev
            - ninja-build
      env: CXX=g++-5
      install:
            - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
            - libwxgtk3.0-dev
            - libxml2-dev
            - libuchardet-dev 
            - libssh-dev
            - libsmbclient-dev
            - libnfs-dev
            - libneon27-dev
            - libarchive-dev
            - ninja-build
      env: CXX=g++-6
      install:
            - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    - os: linux
      dist: xenial
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - cmake
            - libwxgtk3.0-dev
            - libxml2-dev
            - libuchardet-dev 
            - libssh-dev
            - libsmbclient-dev
            - libnfs-dev
            - libneon27-dev
            - libarchive-dev
            - ninja-build
      env: CXX=clang++-3.6
      install:
            - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
    - os: linux
      dist: xenial
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libwxgtk3.0-dev
            - libxml2-dev
            - libuchardet-dev 
            - libssh-dev
            - libsmbclient-dev
            - libnfs-dev
            - libneon27-dev
            - libarchive-dev
            - libpcre2-dev
            - zlib1g-dev
            - ninja-build
      env: CXX=clang++-3.7
      install:
            - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
              
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python@2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ( brew update || brew update || brew update ) ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew pin tmate ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew bundle -v ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:saiarcot895/chromium-beta ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sudo apt-get update ; fi

script:
  - mkdir build
  - cd build
  - cmake -G Ninja .. && ninja -v
  - cd install && zip -r ../far2l-${TRAVIS_COMMIT}.zip * && cd -
