# Continuous Integration with https://travis-ci.org/
language: cpp

# Use Ubuntu 14.04 - https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - libwxgtk3.0-dev
            - libglib2.0-dev
            - gawk
            - m4
            - libpcre3-dev
            - zlib1g-dev
      env: CXX=g++-4.9
      install:
            - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - libwxgtk3.0-dev
            - libglib2.0-dev
            - gawk
            - m4
            - libpcre3-dev
            - zlib1g-dev
      env: CXX=g++-5
      install:
            - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - cmake
            - libwxgtk3.0-dev
            - libglib2.0-dev
            - gawk
            - m4
            - libpcre3-dev
            - zlib1g-dev
      env: CXX=clang++-3.6
      install:
            - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libwxgtk3.0-dev
            - libglib2.0-dev
            - gawk
            - m4
            - libpcre3-dev
            - zlib1g-dev
      env: CXX=clang++-3.7
      install:
            - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

before_install:
  - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
  - sudo apt-get update

install: sudo apt-get install ninja-build

script:
  - mkdir build
  - cd build
  - cmake -G Ninja .. && ninja -j10

